# Generated by Django 4.2 on 2023-04-08 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFieldsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('I', 'Число'), ('S', 'Текст'), ('D', 'Дата'), ('B', 'Файл')], max_length=1, verbose_name='Тип поля')),
            ],
        ),
        migrations.CreateModel(
            name='EstateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('C', 'Центральный'), ('N', 'Северный'), ('NE', 'Северо-Восточный'), ('E', 'Восточный'), ('SE', 'Юго-Восточный'), ('S', 'Южный'), ('SW', 'Юго-Западный'), ('W', 'Западный'), ('NW', 'Северо-Западный'), ('Z', 'Зеленоградский')], max_length=2, verbose_name='Округ')),
                ('district', models.CharField(choices=[('Medvedkovo', 'Медведково'), ('Butovo', 'Бутово'), ('Strogino', 'Строгино'), ('Dorogomilovo', 'Дорогомилово'), ('Otradnoye', 'Отрадное')], max_length=32, verbose_name='Район')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('obj_type', models.CharField(choices=[('liv_building', 'Индивидуальный жилой дом'), ('com_estate', 'Коммерческая недвижимость'), ('land', 'Земельный участок'), ('condo', 'Кондоминимум')], max_length=16, verbose_name='Тип объекта')),
                ('condition', models.CharField(choices=[('ok', 'Исправно'), ('dangerous', 'Авайрийное состояние')], max_length=32, verbose_name='Состояние объекта')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь объекта')),
                ('owner', models.CharField(max_length=256, verbose_name='Собственник')),
                ('current_holder', models.CharField(max_length=256, verbose_name='Фактический пользователь')),
                ('media_files', models.FileField(upload_to='photo_video/', verbose_name='Фото/видео')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(null=True)),
                ('str_value', models.CharField(max_length=256, null=True)),
                ('date_value', models.DateTimeField(null=True)),
                ('binary_value', models.FileField(null=True, upload_to='additional_files/')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_objects.additionalfieldslist')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_objects.estateobject')),
            ],
        ),
    ]
