# Generated by Django 4.2 on 2023-04-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateobject',
            name='division',
            field=models.CharField(choices=[('C', 'Центральный'), ('N', 'Северный'), ('NE', 'Северо-Восточный'), ('E', 'Восточный'), ('SE', 'Юго-Восточный'), ('S', 'Южный'), ('SW', 'Юго-Западный'), ('W', 'Западный'), ('NW', 'Северо-Западный'), ('Z', 'Зеленоградский'), ('T', 'Троицкий'), ('N', 'Новомосковский')], max_length=2, verbose_name='Округ'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Формулировка')),
                ('complete_before', models.DateTimeField(null=True, verbose_name='Срок исполнения')),
                ('responsible', models.CharField(max_length=128, null=True, verbose_name='Ответственный')),
                ('discussion_date', models.DateTimeField(null=True, verbose_name='Дата проведения заседания')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_objects.estateobject', verbose_name='ID объекта')),
            ],
        ),
    ]
